// DOE National Science Bowl - Chemistry Extra Questions (Sets 6-7)

export const CHEMISTRY_HS_EXT = [
  {s:"Chemistry",lv:"HS",set:6,round:1,f:"MC",t:"Organic",q:"What type of isomers have the same molecular formula and bonded sequence but differ in three-dimensional orientation?",o:{W:"Constitutional isomers",X:"Enantiomers",Y:"Resonance structures",Z:"Structural isomers"},a:"X",b:"What is the term for a molecule that is non-superimposable on its mirror image?",ba:"Chiral molecule"},
  {s:"Chemistry",lv:"HS",set:6,round:1,f:"SA",t:"Thermodynamics",q:"What is the formula for Gibbs free energy change?",a:"ΔG = ΔH - TΔS",b:"Under what conditions is a reaction spontaneous in terms of ΔG?",ba:"When ΔG is negative"},
  {s:"Chemistry",lv:"HS",set:6,round:2,f:"MC",t:"Atomic Structure",q:"What is the electron configuration of iron (Fe, atomic number 26)?",o:{W:"[Ar] 3d8",X:"[Ar] 4s2 3d6",Y:"[Kr] 3d6",Z:"[Ar] 4s2 4d6"},a:"X",b:"How many unpaired electrons does iron (Fe) have in its ground state?",ba:"4"},
  {s:"Chemistry",lv:"HS",set:6,round:2,f:"SA",t:"Solutions",q:"What is the relationship between boiling point elevation and molality?",a:"Delta Tb = Kb times m (boiling point elevation constant times molality)",b:"What is the phenomenon by which a solute raises the boiling point of a solvent?",ba:"Boiling point elevation"},
  {s:"Chemistry",lv:"HS",set:6,round:3,f:"MC",t:"Kinetics",q:"What is the integrated rate law for a second-order reaction?",o:{W:"ln[A] = -kt + ln[A]0",X:"[A] = -kt + [A]0",Y:"1/[A] = kt + 1/[A]0",Z:"[A] = [A]0 e^(-kt)"},a:"Y",b:"What is the half-life of a second-order reaction?",ba:"t(1/2) = 1/(k[A]0)"},
  {s:"Chemistry",lv:"HS",set:6,round:3,f:"SA",t:"Electrochemistry",q:"What is the Nernst equation used to calculate?",a:"The cell potential at non-standard conditions",b:"What is the standard cell potential if E cathode = +0.80 V and E anode = -0.44 V?",ba:"1.24 V"},
  {s:"Chemistry",lv:"HS",set:6,round:4,f:"MC",t:"Acids and Bases",q:"What is the pH of a buffer made from equal concentrations of acetic acid (Ka = 1.8e-5) and sodium acetate?",o:{W:"4.74",X:"5.0",Y:"7.0",Z:"9.26"},a:"W",b:"What equation is used to calculate buffer pH?",ba:"Henderson-Hasselbalch equation: pH = pKa + log([A-]/[HA])"},
  {s:"Chemistry",lv:"HS",set:6,round:4,f:"SA",t:"Organic",q:"What is the reaction called when a halogen adds across a carbon-carbon double bond?",a:"Halogenation (electrophilic addition)",b:"What reagent tests for the presence of a carbon-carbon double bond?",ba:"Bromine water (turns colorless)"},
  {s:"Chemistry",lv:"HS",set:6,round:5,f:"SA",t:"Reactions",q:"What is the name of the reaction between an acid and a base that produces salt and water?",a:"Neutralization reaction",b:"What is the net ionic equation for strong acid-strong base neutralization?",ba:"H+ + OH- -> H2O"},
  {s:"Chemistry",lv:"HS",set:6,round:5,f:"MC",t:"Periodic Table",q:"Which element has the largest atomic radius in the periodic table?",o:{W:"Francium",X:"Cesium",Y:"Barium",Z:"Radon"},a:"W",b:"Why does atomic radius increase going down a group?",ba:"More electron shells are added"},
  {s:"Chemistry",lv:"HS",set:7,round:1,f:"MC",t:"Bonding",q:"Which of the following molecules has a trigonal bipyramidal geometry?",o:{W:"NH3",X:"PCl5",Y:"SF4",Z:"BrF3"},a:"X",b:"What is the electron geometry of SF4?",ba:"Trigonal bipyramidal"},
  {s:"Chemistry",lv:"HS",set:7,round:1,f:"SA",t:"Stoichiometry",q:"What is the percent yield if a reaction produces 18 g of product when 25 g was theoretically expected?",a:"72%",b:"What is the formula for percent yield?",ba:"(actual yield / theoretical yield) x 100%"},
  {s:"Chemistry",lv:"HS",set:7,round:2,f:"MC",t:"Equilibrium",q:"If Keq > 1 for a reaction, what does this indicate?",o:{W:"Reactants are favored",X:"Products are favored",Y:"The reaction does not proceed",Z:"The activation energy is low"},a:"X",b:"What is the Keq for the reverse of a reaction if Keq(forward) = 4?",ba:"0.25"},
  {s:"Chemistry",lv:"HS",set:7,round:2,f:"SA",t:"Nuclear",q:"What is the energy that must be overcome to split a nucleus into individual protons and neutrons?",a:"Nuclear binding energy",b:"What is the relationship between binding energy per nucleon and nuclear stability?",ba:"Higher binding energy per nucleon means greater stability"},
  {s:"Chemistry",lv:"HS",set:7,round:3,f:"MC",t:"Gases",q:"At what temperature does a gas theoretically have zero kinetic energy?",o:{W:"0 Celsius",X:"273 K",Y:"0 K",Z:"-100 Celsius"},a:"Y",b:"What is the root mean square speed of gas molecules proportional to?",ba:"Square root of temperature divided by molar mass"},
  {s:"Chemistry",lv:"HS",set:7,round:3,f:"SA",t:"Organic",q:"What is the reaction called when a benzene ring substitutes a hydrogen for a group in the presence of a Lewis acid?",a:"Electrophilic aromatic substitution",b:"What is the most common Lewis acid catalyst used in Friedel-Crafts alkylation?",ba:"AlCl3"},
  {s:"Chemistry",lv:"HS",set:7,round:4,f:"SA",t:"Solutions",q:"What is the molar solubility of AgCl if its Ksp = 1.8e-10?",a:"1.34e-5 M",b:"What is the Ksp expression for AgCl?",ba:"Ksp = [Ag+][Cl-]"},
  {s:"Chemistry",lv:"HS",set:7,round:4,f:"MC",t:"Thermodynamics",q:"A reaction has ΔH = -100 kJ/mol and ΔS = -200 J/(mol·K). At what temperature does the reaction become non-spontaneous?",o:{W:"Below 500 K",X:"Above 500 K",Y:"Below 200 K",Z:"Above 200 K"},a:"X",b:"What is the formula for the temperature at which ΔG = 0?",ba:"T = ΔH/ΔS"},
  {s:"Chemistry",lv:"HS",set:7,round:5,f:"MC",t:"Atomic Structure",q:"What principle states that electrons occupy the lowest energy orbitals available?",o:{W:"Pauli exclusion principle",X:"Hund's rule",Y:"Aufbau principle",Z:"Heisenberg uncertainty principle"},a:"Y",b:"What does Hund's rule state about filling degenerate orbitals?",ba:"Electrons fill each degenerate orbital singly before pairing"},
  {s:"Chemistry",lv:"HS",set:7,round:5,f:"SA",t:"Kinetics",q:"What is the intermediate species at the peak of an energy diagram called?",a:"Transition state (activated complex)",b:"How does a catalyst affect activation energy?",ba:"It lowers the activation energy"},
];