// DOE National Science Bowl - Earth & Space Science Questions

export const EARTH_SPACE_HS = [
  // SET 1
  {s:"Earth & Space",lv:"HS",set:1,round:1,f:"MC",t:"Geology",q:"What type of rock is formed from cooled magma or lava?",o:{W:"Sedimentary",X:"Metamorphic",Y:"Igneous",Z:"Composite"},a:"Y",b:"What is the name of the layer of Earth located between the crust and the outer core?",ba:"Mantle"},
  {s:"Earth & Space",lv:"HS",set:1,round:1,f:"MC",t:"Astronomy",q:"What is the term for the point in a planet's orbit closest to the Sun?",o:{W:"Aphelion",X:"Perihelion",Y:"Apogee",Z:"Perigee"},a:"X",b:"What is the name of the law that states planets sweep equal areas in equal times?",ba:"Kepler's second law"},
  {s:"Earth & Space",lv:"HS",set:1,round:2,f:"SA",t:"Atmosphere",q:"What is the name of the layer of Earth's atmosphere that contains the ozone layer?",a:"Stratosphere",b:"What gas makes up approximately 78% of Earth's atmosphere?",ba:"Nitrogen"},
  {s:"Earth & Space",lv:"HS",set:1,round:2,f:"MC",t:"Plate Tectonics",q:"What type of plate boundary occurs when two plates move apart from each other?",o:{W:"Convergent",X:"Transform",Y:"Subduction",Z:"Divergent"},a:"Z",b:"What is the name of the supercontinent that existed approximately 300 million years ago?",ba:"Pangaea"},
  {s:"Earth & Space",lv:"HS",set:1,round:3,f:"MC",t:"Astronomy",q:"What type of star is our Sun classified as on the Hertzsprung-Russell diagram?",o:{W:"Red giant",X:"White dwarf",Y:"Main sequence",Z:"Neutron star"},a:"Y",b:"What is the name of the galaxy that contains our solar system?",ba:"Milky Way"},
  {s:"Earth & Space",lv:"HS",set:1,round:3,f:"SA",t:"Geology",q:"What is the term for the boundary between Earth's crust and mantle?",a:"Mohorovicic discontinuity (Moho)",b:"What scale measures the magnitude of earthquakes?",ba:"Richter scale (or moment magnitude scale)"},
  {s:"Earth & Space",lv:"HS",set:1,round:4,f:"MC",t:"Oceanography",q:"What drives the thermohaline circulation of the world's oceans?",o:{W:"Wind patterns",X:"Earth's rotation",Y:"Differences in water temperature and salinity",Z:"Tidal forces"},a:"Y",b:"What is the deepest point in Earth's oceans?",ba:"Challenger Deep (Mariana Trench)"},
  {s:"Earth & Space",lv:"HS",set:1,round:4,f:"SA",t:"Atmosphere",q:"What is the name of the phenomenon where heat is trapped in Earth's atmosphere by greenhouse gases?",a:"Greenhouse effect",b:"Which greenhouse gas is produced in the largest quantities by human activity?",ba:"Carbon dioxide (CO₂)"},
  {s:"Earth & Space",lv:"HS",set:1,round:5,f:"MC",t:"Geology",q:"What type of seismic wave cannot travel through liquids?",o:{W:"P-waves",X:"Surface waves",Y:"Love waves",Z:"S-waves"},a:"Z",b:"What is the term for molten rock beneath Earth's surface?",ba:"Magma"},
  {s:"Earth & Space",lv:"HS",set:1,round:5,f:"SA",t:"Geology",q:"What process breaks down rocks at Earth's surface through physical and chemical means?",a:"Weathering",b:"What is the term for the process by which sediment is carried away by water or wind?",ba:"Erosion"},
  // SET 2
  {s:"Earth & Space",lv:"HS",set:2,round:1,f:"MC",t:"Astronomy",q:"Which planet in our solar system has the most moons?",o:{W:"Jupiter",X:"Saturn",Y:"Uranus",Z:"Neptune"},a:"X",b:"What is the name of Saturn's largest moon, which has a thick atmosphere?",ba:"Titan"},
  {s:"Earth & Space",lv:"HS",set:2,round:1,f:"SA",t:"Atmosphere",q:"What is the name of the boundary between the troposphere and stratosphere?",a:"Tropopause",b:"At what altitude approximately does the troposphere end?",ba:"~12 km"},
  {s:"Earth & Space",lv:"HS",set:2,round:2,f:"MC",t:"Plate Tectonics",q:"What is formed when an oceanic plate subducts beneath a continental plate?",o:{W:"Mid-ocean ridge",X:"Rift valley",Y:"Transform fault",Z:"Volcanic arc"},a:"Z",b:"What is the name for a chain of volcanoes that forms above a subducting plate?",ba:"Island arc"},
  {s:"Earth & Space",lv:"HS",set:2,round:2,f:"SA",t:"Geology",q:"What is the name of the process by which magma rises to the surface and creates new oceanic crust?",a:"Seafloor spreading",b:"Where does seafloor spreading primarily occur?",ba:"Mid-ocean ridges"},
  {s:"Earth & Space",lv:"HS",set:2,round:3,f:"MC",t:"Astronomy",q:"What is the Hertzsprung-Russell diagram used to show?",o:{W:"The orbits of planets",X:"The relationship between stellar luminosity and temperature",Y:"The distances between stars",Z:"The composition of stars"},a:"X",b:"What type of stars are found in the lower-left of the H-R diagram?",ba:"White dwarfs"},
  {s:"Earth & Space",lv:"HS",set:2,round:3,f:"SA",t:"Atmosphere",q:"What is the name of the circulation pattern in the atmosphere driven by temperature differences at the equator and poles?",a:"Hadley cells (atmospheric circulation cells)",b:"What are the narrow bands of fast-moving air at high altitude in the atmosphere called?",ba:"Jet streams"},
  {s:"Earth & Space",lv:"HS",set:2,round:4,f:"MC",t:"Astronomy",q:"What type of object is formed when a massive star collapses after a supernova?",o:{W:"White dwarf",X:"Red giant",Y:"Neutron star or black hole",Z:"Brown dwarf"},a:"Y",b:"What is the name of the boundary around a black hole beyond which nothing can escape?",ba:"Event horizon"},
  {s:"Earth & Space",lv:"HS",set:2,round:4,f:"SA",t:"Geology",q:"What type of rock forms when existing rocks are changed by heat and pressure?",a:"Metamorphic rock",b:"What is the term for the process by which sediments become compacted and cemented into rock?",ba:"Lithification"},
  {s:"Earth & Space",lv:"HS",set:2,round:5,f:"MC",t:"Oceanography",q:"What is the term for the layer of ocean water that separates the warmer surface water from the deeper cold water?",o:{W:"Thermocline",X:"Pycnocline",Y:"Halocline",Z:"Photic zone"},a:"W",b:"What is the photic zone?",ba:"The sunlit upper layer of the ocean where photosynthesis can occur"},
  {s:"Earth & Space",lv:"HS",set:2,round:5,f:"SA",t:"Astronomy",q:"What is the name of the point in space where the gravitational force from two massive bodies is equal?",a:"Lagrange point",b:"What is the term for the wobble of Earth's axis with a period of about 26,000 years?",ba:"Precession"},
  // SET 3
  {s:"Earth & Space",lv:"HS",set:3,round:1,f:"MC",t:"Geology",q:"What is the name of the rock cycle process by which sediment accumulates in layers?",o:{W:"Metamorphism",X:"Volcanism",Y:"Erosion",Z:"Deposition"},a:"Z",b:"What are the three main types of sedimentary rock classified by?",ba:"Their origin (clastic, chemical, or organic/biogenic)"},
  {s:"Earth & Space",lv:"HS",set:3,round:1,f:"SA",t:"Atmosphere",q:"What is the term for air rising near the equator and descending near 30° latitude?",a:"Hadley cell",b:"What weather phenomenon is associated with low pressure systems?",ba:"Cyclones (and precipitation)"},
  {s:"Earth & Space",lv:"HS",set:3,round:2,f:"MC",t:"Astronomy",q:"What is the approximate distance from Earth to the Sun?",o:{W:"1 light-year",X:"1 astronomical unit",Y:"1 parsec",Z:"1 light-minute"},a:"X",b:"How long does light take to travel from the Sun to Earth?",ba:"About 8 minutes"},
  {s:"Earth & Space",lv:"HS",set:3,round:2,f:"SA",t:"Plate Tectonics",q:"What type of boundary occurs when two continental plates collide?",a:"Convergent boundary (continent-continent collision)",b:"What mountain range was formed by the collision of the Indian and Eurasian plates?",ba:"Himalayas"},
  {s:"Earth & Space",lv:"HS",set:3,round:3,f:"MC",t:"Geology",q:"Which of the following is an example of a chemical sedimentary rock?",o:{W:"Sandstone",X:"Shale",Y:"Conglomerate",Z:"Limestone"},a:"Z",b:"What mineral makes up most limestone?",ba:"Calcite"},
  {s:"Earth & Space",lv:"HS",set:3,round:3,f:"SA",t:"Astronomy",q:"What is the term for the point in a star's life when it runs out of hydrogen fuel in its core?",a:"When it leaves the main sequence (begins to become a red giant)",b:"What will happen to the Sun when it runs out of hydrogen?",ba:"It will expand into a red giant"},
  {s:"Earth & Space",lv:"HS",set:3,round:4,f:"MC",t:"Oceanography",q:"What is the name of the current that flows northward along the East Coast of the United States?",o:{W:"Labrador Current",X:"California Current",Y:"Gulf Stream",Z:"North Atlantic Current"},a:"Y",b:"What drives surface ocean currents?",ba:"Wind patterns (and Earth's rotation via Coriolis effect)"},
  {s:"Earth & Space",lv:"HS",set:3,round:4,f:"SA",t:"Atmosphere",q:"What is the name of the semi-permanent high pressure system over the subtropical Atlantic Ocean?",a:"Bermuda High (Azores High)",b:"What is the term for the clockwise rotation of winds around a high pressure system in the Northern Hemisphere?",ba:"Anticyclone"},
  {s:"Earth & Space",lv:"HS",set:3,round:5,f:"MC",t:"Geology",q:"What is the age of Earth, approximately?",o:{W:"4.5 thousand years",X:"4.5 million years",Y:"4.5 billion years",Z:"45 billion years"},a:"Y",b:"What is the name of the method used to determine the age of rocks using radioactive isotopes?",ba:"Radiometric dating"},
  {s:"Earth & Space",lv:"HS",set:3,round:5,f:"SA",t:"Astronomy",q:"What is the name of the force that causes the formation of stars from clouds of gas and dust?",a:"Gravity",b:"What is the approximate age of the universe?",ba:"13.8 billion years"},
  // SET 4
  {s:"Earth & Space",lv:"HS",set:4,round:1,f:"MC",t:"Atmosphere",q:"What is the main cause of the seasons on Earth?",o:{W:"Earth's distance from the Sun",X:"The tilt of Earth's axis",Y:"Sunspot activity",Z:"The speed of Earth's rotation"},a:"X",b:"How many degrees is Earth's axial tilt?",ba:"23.5°"},
  {s:"Earth & Space",lv:"HS",set:4,round:1,f:"SA",t:"Geology",q:"What is the term for a body of rock that has moved along a fault?",a:"Fault block",b:"What type of fault occurs when rocks are compressed and one block moves up relative to another?",ba:"Reverse fault (thrust fault)"},
  {s:"Earth & Space",lv:"HS",set:4,round:2,f:"MC",t:"Astronomy",q:"What type of galaxy is the Milky Way?",o:{W:"Elliptical",X:"Irregular",Y:"Spiral",Z:"Lenticular"},a:"Y",b:"What is at the center of the Milky Way?",ba:"A supermassive black hole (Sagittarius A*)"},
  {s:"Earth & Space",lv:"HS",set:4,round:2,f:"SA",t:"Oceanography",q:"What is the term for the daily rise and fall of sea levels caused by the gravitational pull of the Moon and Sun?",a:"Tides",b:"What type of tides occur when the Sun, Moon, and Earth are aligned?",ba:"Spring tides"},
  {s:"Earth & Space",lv:"HS",set:4,round:3,f:"MC",t:"Plate Tectonics",q:"What is the name of the theory that explains the movement of Earth's lithospheric plates?",o:{W:"Continental drift",X:"Seafloor spreading",Y:"Plate tectonics",Z:"Isostasy"},a:"Y",b:"Who first proposed continental drift?",ba:"Alfred Wegener"},
  {s:"Earth & Space",lv:"HS",set:4,round:3,f:"SA",t:"Atmosphere",q:"What is the name of the warming phenomenon caused by the weakening of trade winds in the Pacific?",a:"El Niño",b:"What is the counterpart cooling phenomenon called?",ba:"La Niña"},
  {s:"Earth & Space",lv:"HS",set:4,round:4,f:"MC",t:"Astronomy",q:"What is the name of the theory that describes the origin of the universe?",o:{W:"Steady state theory",X:"Big Bang theory",Y:"Nebular hypothesis",Z:"Oscillating universe theory"},a:"X",b:"What is the cosmic microwave background radiation evidence for?",ba:"The Big Bang"},
  {s:"Earth & Space",lv:"HS",set:4,round:4,f:"SA",t:"Geology",q:"What is the name of the layer of Earth composed of solid iron and nickel?",a:"Inner core",b:"What is the radius of Earth's inner core approximately?",ba:"~1,220 km"},
  {s:"Earth & Space",lv:"HS",set:4,round:5,f:"MC",t:"Atmosphere",q:"Which gas in the atmosphere is responsible for absorbing ultraviolet radiation?",o:{W:"Oxygen",X:"Nitrogen",Y:"Ozone",Z:"Carbon dioxide"},a:"Y",b:"What chemicals are known to destroy stratospheric ozone?",ba:"Chlorofluorocarbons (CFCs)"},
  {s:"Earth & Space",lv:"HS",set:4,round:5,f:"SA",t:"Astronomy",q:"What is the term for the spinning of a planet on its own axis?",a:"Rotation",b:"What causes the Coriolis effect?",ba:"Earth's rotation"},
];

export const EARTH_SPACE_MS = [
  {s:"Earth & Space",lv:"MS",set:1,round:1,f:"MC",t:"Solar System",q:"Which planet is closest to the Sun?",o:{W:"Venus",X:"Earth",Y:"Mercury",Z:"Mars"},a:"Y",b:"What is the largest planet in our solar system?",ba:"Jupiter"},
  {s:"Earth & Space",lv:"MS",set:1,round:1,f:"SA",t:"Geology",q:"What is the layer of Earth that we live on called?",a:"Crust",b:"What is the liquid rock beneath Earth's surface called?",ba:"Magma"},
  {s:"Earth & Space",lv:"MS",set:1,round:2,f:"MC",t:"Weather",q:"What instrument measures air pressure?",o:{W:"Thermometer",X:"Barometer",Y:"Hygrometer",Z:"Anemometer"},a:"X",b:"What is the name of the boundary between two air masses?",ba:"Front"},
  {s:"Earth & Space",lv:"MS",set:1,round:2,f:"SA",t:"Astronomy",q:"What is the name of the galaxy that contains our solar system?",a:"Milky Way",b:"What is a star in its final stage of life that has collapsed and is very dense called?",ba:"White dwarf"},
  {s:"Earth & Space",lv:"MS",set:2,round:1,f:"MC",t:"Plate Tectonics",q:"What causes earthquakes?",o:{W:"Volcanic eruptions",X:"Movement of tectonic plates",Y:"Ocean tides",Z:"Changes in weather"},a:"X",b:"What instrument measures the magnitude of earthquakes?",ba:"Seismograph"},
  {s:"Earth & Space",lv:"MS",set:2,round:1,f:"SA",t:"Geology",q:"What are the three main types of rock?",a:"Igneous, sedimentary, and metamorphic",b:"What type of rock forms from cooled lava?",ba:"Igneous rock"},
  {s:"Earth & Space",lv:"MS",set:2,round:2,f:"MC",t:"Solar System",q:"What is the name of the path Earth takes around the Sun?",o:{W:"Revolution",X:"Rotation",Y:"Orbit",Z:"Ellipse"},a:"Y",b:"How long does it take Earth to orbit the Sun?",ba:"365.25 days"},
  {s:"Earth & Space",lv:"MS",set:3,round:1,f:"SA",t:"Atmosphere",q:"What is the name of the layer of Earth's atmosphere closest to Earth's surface?",a:"Troposphere",b:"Where does most weather occur?",ba:"Troposphere"},
];