// DOE National Science Bowl - Energy Questions

export const ENERGY_HS = [
  // SET 1
  {s:"Energy",lv:"HS",set:1,round:1,f:"MC",t:"Nuclear",q:"What type of nuclear reaction powers the Sun?",o:{W:"Fission",X:"Fusion",Y:"Radioactive decay",Z:"Combustion"},a:"X",b:"What is the fuel used in most current nuclear power plants?",ba:"Uranium-235"},
  {s:"Energy",lv:"HS",set:1,round:1,f:"MC",t:"Solar",q:"What effect is used by photovoltaic cells to convert sunlight into electricity?",o:{W:"Thermoelectric effect",X:"Electromagnetic induction",Y:"Photoelectric effect",Z:"Piezoelectric effect"},a:"Y",b:"What is the approximate efficiency of a typical commercial silicon solar cell?",ba:"15–20%"},
  {s:"Energy",lv:"HS",set:1,round:2,f:"SA",t:"Thermodynamics",q:"What device converts mechanical energy into electrical energy using electromagnetic induction?",a:"Generator",b:"What is the name of the law that describes energy conversion efficiency limits?",ba:"Second law of thermodynamics"},
  {s:"Energy",lv:"HS",set:1,round:2,f:"MC",t:"Fossil Fuels",q:"What is the primary component of natural gas?",o:{W:"Ethane",X:"Propane",Y:"Methane",Z:"Butane"},a:"Y",b:"What is the term for the liquid mixture of hydrocarbons refined to make gasoline?",ba:"Petroleum (crude oil)"},
  {s:"Energy",lv:"HS",set:1,round:3,f:"MC",t:"Renewable",q:"What type of energy is produced by harnessing the flow of water?",o:{W:"Geothermal",X:"Wind",Y:"Tidal",Z:"Hydroelectric"},a:"Z",b:"What is the name of the world's largest hydroelectric dam?",ba:"Three Gorges Dam"},
  {s:"Energy",lv:"HS",set:1,round:3,f:"SA",t:"Electricity",q:"What is the name of the network of transmission lines that delivers electricity from power plants to homes?",a:"Electrical grid (or power grid)",b:"What is the formula for electrical power?",ba:"P = IV (or P = I²R or P = V²/R)"},
  {s:"Energy",lv:"HS",set:1,round:4,f:"MC",t:"Nuclear",q:"In nuclear fission, when a uranium-235 nucleus absorbs a neutron, what happens?",o:{W:"It emits a photon",X:"It splits into smaller nuclei releasing energy",Y:"It undergoes beta decay",Z:"It becomes uranium-236 and is stable"},a:"X",b:"What is the term for the minimum mass of fissile material needed to sustain a chain reaction?",ba:"Critical mass"},
  {s:"Energy",lv:"HS",set:1,round:4,f:"MC",t:"Renewable",q:"What is the most abundant source of renewable energy used for electricity generation worldwide?",o:{W:"Solar",X:"Wind",Y:"Hydropower",Z:"Geothermal"},a:"Y",b:"What is the Betz limit — the theoretical maximum efficiency of a wind turbine?",ba:"59.3%"},
  {s:"Energy",lv:"HS",set:1,round:5,f:"SA",t:"Thermodynamics",q:"What is the term for energy stored in chemical bonds that is released during combustion?",a:"Chemical energy",b:"What unit is used to measure energy content of food?",ba:"Calorie (or kilocalorie)"},
  {s:"Energy",lv:"HS",set:1,round:5,f:"SA",t:"Nuclear",q:"What is the term for the energy equivalent of mass described by Einstein's equation E = mc²?",a:"Mass-energy equivalence",b:"What is the speed of light in E = mc²?",ba:"3 × 10⁸ m/s"},
  // SET 2
  {s:"Energy",lv:"HS",set:2,round:1,f:"MC",t:"Fossil Fuels",q:"Which fossil fuel has the highest energy density per unit mass?",o:{W:"Coal",X:"Natural gas",Y:"Petroleum",Z:"Peat"},a:"X",b:"What is the main environmental concern associated with burning fossil fuels?",ba:"Carbon dioxide emissions and climate change"},
  {s:"Energy",lv:"HS",set:2,round:1,f:"SA",t:"Renewable",q:"What is the term for electricity generated from the heat of the Earth's interior?",a:"Geothermal energy",b:"Which US state produces the most geothermal electricity?",ba:"California"},
  {s:"Energy",lv:"HS",set:2,round:2,f:"MC",t:"Electricity",q:"What does AC stand for in the context of electrical power?",o:{W:"Absolute current",X:"Alternating current",Y:"Atomic charge",Z:"Ampere current"},a:"X",b:"What frequency is alternating current in the United States?",ba:"60 Hz"},
  {s:"Energy",lv:"HS",set:2,round:2,f:"SA",t:"Nuclear",q:"What are the byproducts released when uranium-235 undergoes fission with a neutron?",a:"Smaller nuclei (fission fragments) and neutrons (plus energy/gamma rays)",b:"What is the term for nuclear waste that remains radioactive for thousands of years?",ba:"High-level radioactive waste"},
  {s:"Energy",lv:"HS",set:2,round:3,f:"MC",t:"Solar",q:"What is the name of the process by which plants convert solar energy into chemical energy?",o:{W:"Chemosynthesis",X:"Fermentation",Y:"Cellular respiration",Z:"Photosynthesis"},a:"Z",b:"What pigment in plants primarily absorbs sunlight for photosynthesis?",ba:"Chlorophyll"},
  {s:"Energy",lv:"HS",set:2,round:3,f:"SA",t:"Thermodynamics",q:"What is the Carnot efficiency formula?",a:"η = 1 - (T_cold/T_hot)",b:"What is the maximum theoretical efficiency of a heat engine operating between 600 K and 300 K?",ba:"50%"},
  {s:"Energy",lv:"HS",set:2,round:4,f:"MC",t:"Nuclear",q:"What is the term for the chain reaction in which each fission event produces neutrons that cause further fissions?",o:{W:"Critical reaction",X:"Controlled fusion",Y:"Nuclear chain reaction",Z:"Beta cascade"},a:"Y",b:"What material is used in a nuclear reactor to slow down neutrons to maintain a controlled reaction?",ba:"Moderator (e.g., water, heavy water, or graphite)"},
  {s:"Energy",lv:"HS",set:2,round:4,f:"SA",t:"Renewable",q:"What is the term for the storage of electrical energy in a chemical form?",a:"Electrochemical energy storage (or battery)",b:"What is the basic unit of voltage called?",ba:"Volt"},
  {s:"Energy",lv:"HS",set:2,round:5,f:"MC",t:"Fossil Fuels",q:"What is the main process by which coal is formed?",o:{W:"Photosynthesis of ancient forests",X:"Burial and compression of ancient plant material over millions of years",Y:"Crystallization of minerals from ancient seas",Z:"Volcanic activity"},a:"X",b:"What is the highest rank of coal with the highest carbon content?",ba:"Anthracite"},
  {s:"Energy",lv:"HS",set:2,round:5,f:"SA",t:"Electricity",q:"What is the term for the opposition to alternating current in a capacitor or inductor?",a:"Reactance",b:"What is the combined opposition to AC current called?",ba:"Impedance"},
  // SET 3
  {s:"Energy",lv:"HS",set:3,round:1,f:"MC",t:"Solar",q:"What is the name of the phenomenon by which a heated material emits radiation?",o:{W:"Photoelectric effect",X:"Blackbody radiation",Y:"Compton scattering",Z:"Fluorescence"},a:"X",b:"What law describes the wavelength at which a blackbody emits peak radiation?",ba:"Wien's displacement law"},
  {s:"Energy",lv:"HS",set:3,round:1,f:"SA",t:"Renewable",q:"What is the term for the ratio of useful energy output to total energy input?",a:"Efficiency",b:"A power plant produces 400 MW of electricity from 1000 MW of thermal energy. What is its efficiency?",ba:"40%"},
  {s:"Energy",lv:"HS",set:3,round:2,f:"MC",t:"Nuclear",q:"What is the binding energy per nucleon greatest for?",o:{W:"Hydrogen",X:"Helium",Y:"Iron-56",Z:"Uranium-238"},a:"Y",b:"What is released during nuclear fusion of hydrogen isotopes?",ba:"Energy (and helium-4 plus neutrons)"},
  {s:"Energy",lv:"HS",set:3,round:2,f:"SA",t:"Electricity",q:"What is the term for the energy stored in a magnetic field?",a:"Magnetic energy",b:"What is the formula for energy stored in an inductor?",ba:"E = ½LI²"},
  {s:"Energy",lv:"HS",set:3,round:3,f:"MC",t:"Fossil Fuels",q:"What is the term for the process of converting coal to synthetic gas?",o:{W:"Fracking",X:"Hydrocracking",Y:"Coal gasification",Z:"Pyrolysis"},a:"Y",b:"What is hydraulic fracturing (fracking) used to extract?",ba:"Natural gas and oil from tight rock formations"},
  {s:"Energy",lv:"HS",set:3,round:3,f:"SA",t:"Renewable",q:"What is the name of the energy stored in a reservoir of water above a turbine?",a:"Gravitational potential energy",b:"What is the formula for power generated by a water turbine given flow rate Q, density ρ, gravity g, and head h?",ba:"P = ρQgh"},
  {s:"Energy",lv:"HS",set:3,round:4,f:"MC",t:"Nuclear",q:"What is the half-life of carbon-14?",o:{W:"1,000 years",X:"5,730 years",Y:"14,000 years",Z:"100,000 years"},a:"X",b:"What technique uses carbon-14 to determine the age of organic materials?",ba:"Radiocarbon dating"},
  {s:"Energy",lv:"HS",set:3,round:4,f:"SA",t:"Solar",q:"What are the two main types of solar thermal energy systems?",a:"Concentrating solar power (CSP) and flat-plate collectors",b:"What is the name of the molten salt storage system used in CSP plants?",ba:"Thermal energy storage (TES)"},
  {s:"Energy",lv:"HS",set:3,round:5,f:"MC",t:"Electricity",q:"What is the unit of electrical energy?",o:{W:"Watt",X:"Ampere",Y:"Joule",Z:"Volt"},a:"Y",b:"What is a kilowatt-hour (kWh) in joules?",ba:"3.6 × 10⁶ J"},
  {s:"Energy",lv:"HS",set:3,round:5,f:"SA",t:"Thermodynamics",q:"What is the name of the law that states entropy of a perfect crystal at absolute zero is zero?",a:"Third law of thermodynamics",b:"What is the symbol used to represent entropy?",ba:"S"},
  // SET 4
  {s:"Energy",lv:"HS",set:4,round:1,f:"MC",t:"Renewable",q:"What is the name of the phenomenon by which ocean temperature differences are used to generate electricity?",o:{W:"Tidal power",X:"Wave energy",Y:"Ocean thermal energy conversion (OTEC)",Z:"Salinity gradient energy"},a:"Y",b:"What is the minimum temperature difference needed for OTEC to be viable?",ba:"About 20°C"},
  {s:"Energy",lv:"HS",set:4,round:1,f:"SA",t:"Nuclear",q:"What is the difference between nuclear fission and nuclear fusion?",a:"Fission splits heavy nuclei; fusion combines light nuclei",b:"Which releases more energy per unit mass of fuel?",ba:"Fusion"},
  {s:"Energy",lv:"HS",set:4,round:2,f:"MC",t:"Fossil Fuels",q:"What is the primary greenhouse gas released by burning natural gas?",o:{W:"Carbon monoxide",X:"Carbon dioxide",Y:"Methane",Z:"Nitrogen dioxide"},a:"X",b:"What is the greenhouse warming potential of methane compared to CO₂ over 100 years?",ba:"About 25-28 times greater"},
  {s:"Energy",lv:"HS",set:4,round:2,f:"SA",t:"Electricity",q:"What is the name of the device that converts DC power to AC power?",a:"Inverter",b:"What converts AC to DC?",ba:"Rectifier"},
  {s:"Energy",lv:"HS",set:4,round:3,f:"MC",t:"Solar",q:"What is the name of the solar technology that uses mirrors or lenses to concentrate sunlight onto a small area?",o:{W:"Photovoltaic system",X:"Concentrating solar power (CSP)",Y:"Solar water heating",Z:"Passive solar design"},a:"X",b:"What is the name of the tower-based CSP system?",ba:"Power tower (or central receiver system)"},
  {s:"Energy",lv:"HS",set:4,round:3,f:"SA",t:"Renewable",q:"What is the name for energy produced from organic materials such as wood, crops, and waste?",a:"Biomass energy (bioenergy)",b:"What liquid fuel is produced from the fermentation of sugars by microorganisms?",ba:"Ethanol"},
  {s:"Energy",lv:"HS",set:4,round:4,f:"MC",t:"Nuclear",q:"What is the purpose of the containment building in a nuclear power plant?",o:{W:"To house the turbines",X:"To prevent radiation from escaping in case of accident",Y:"To store nuclear waste",Z:"To generate steam"},a:"X",b:"What is the name of the cooling system that prevents nuclear reactor meltdown?",ba:"Emergency core cooling system (ECCS)"},
  {s:"Energy",lv:"HS",set:4,round:4,f:"SA",t:"Electricity",q:"What is the name of a device that increases or decreases AC voltage?",a:"Transformer",b:"What principle does a transformer operate on?",ba:"Electromagnetic induction (Faraday's law)"},
  {s:"Energy",lv:"HS",set:4,round:5,f:"MC",t:"Thermodynamics",q:"What is the name of the cycle used in coal power plants?",o:{W:"Otto cycle",X:"Brayton cycle",Y:"Rankine cycle",Z:"Carnot cycle"},a:"Y",b:"What cycle is used in gas turbine power plants?",ba:"Brayton cycle"},
  {s:"Energy",lv:"HS",set:4,round:5,f:"SA",t:"Renewable",q:"What is the name of the tidal energy device that uses the rise and fall of water to turn a turbine?",a:"Tidal barrage",b:"What is the alternative tidal device that works like an underwater wind turbine?",ba:"Tidal stream generator (tidal turbine)"},
];

export const ENERGY_MS = [
  {s:"Energy",lv:"MS",set:1,round:1,f:"MC",t:"Renewable Energy",q:"Which of the following is a renewable energy source?",o:{W:"Coal",X:"Natural gas",Y:"Solar",Z:"Oil"},a:"Y",b:"What renewable energy source uses the flow of water?",ba:"Hydroelectric power"},
  {s:"Energy",lv:"MS",set:1,round:1,f:"SA",t:"Energy Types",q:"What form of energy is stored in food and fuels?",a:"Chemical energy",b:"What is the energy of motion called?",ba:"Kinetic energy"},
  {s:"Energy",lv:"MS",set:1,round:2,f:"MC",t:"Electricity",q:"What does a battery convert chemical energy into?",o:{W:"Thermal energy",X:"Electrical energy",Y:"Nuclear energy",Z:"Mechanical energy"},a:"X",b:"What is the unit of electrical power?",ba:"Watt"},
  {s:"Energy",lv:"MS",set:1,round:2,f:"SA",t:"Energy Types",q:"What type of energy is found in the nucleus of an atom?",a:"Nuclear energy",b:"What is the law that states energy cannot be created or destroyed?",ba:"Law of Conservation of Energy"},
  {s:"Energy",lv:"MS",set:2,round:1,f:"MC",t:"Fossil Fuels",q:"Which of the following is NOT a fossil fuel?",o:{W:"Coal",X:"Natural gas",Y:"Wood",Z:"Petroleum"},a:"Y",b:"Why are fossil fuels called non-renewable?",ba:"They take millions of years to form and cannot be replenished quickly"},
  {s:"Energy",lv:"MS",set:2,round:1,f:"SA",t:"Renewable Energy",q:"What is the term for the energy from the heat inside the Earth?",a:"Geothermal energy",b:"What is the device that converts wind energy to electricity called?",ba:"Wind turbine"},
  {s:"Energy",lv:"MS",set:2,round:2,f:"MC",t:"Electricity",q:"What is the unit of voltage?",o:{W:"Ampere",X:"Watt",Y:"Ohm",Z:"Volt"},a:"Z",b:"What is the formula for Ohm's Law?",ba:"V = IR"},
  {s:"Energy",lv:"MS",set:3,round:1,f:"SA",t:"Energy Types",q:"What is the term for energy stored in a stretched spring or rubber band?",a:"Elastic potential energy",b:"What type of energy does a waterfall have before it falls?",ba:"Gravitational potential energy"},
];