// DOE National Science Bowl - Math Extra Questions (Sets 5-6)

export const MATH_HS_EXT = [
  {s:"Math",lv:"HS",set:5,round:1,f:"MC",t:"Calculus",q:"What is the derivative of arctan(x)?",o:{W:"1/(1+x^2)",X:"1/sqrt(1-x^2)",Y:"-1/(1+x^2)",Z:"1/x"},a:"W",b:"What is the derivative of arcsin(x)?",ba:"1/sqrt(1-x^2)"},
  {s:"Math",lv:"HS",set:5,round:1,f:"SA",t:"Number Theory",q:"What is Euler's totient function phi(12)?",a:"4",b:"What is phi(p) for a prime p?",ba:"p - 1"},
  {s:"Math",lv:"HS",set:5,round:2,f:"MC",t:"Linear Algebra",q:"What is the determinant of the 2x2 matrix [[2,3],[1,4]]?",o:{W:"5",X:"8",Y:"11",Z:"14"},a:"W",b:"A matrix with determinant 0 is called what?",ba:"Singular (non-invertible)"},
  {s:"Math",lv:"HS",set:5,round:2,f:"SA",t:"Calculus",q:"What is the integral of 1/x dx?",a:"ln|x| + C",b:"What is the integral of e^x?",ba:"e^x + C"},
  {s:"Math",lv:"HS",set:5,round:3,f:"MC",t:"Statistics",q:"What is the z-score of a data point that is 2 standard deviations above the mean?",o:{W:"0",X:"1",Y:"2",Z:"4"},a:"Y",b:"What percentage of data falls within 1 standard deviation of the mean in a normal distribution?",ba:"About 68%"},
  {s:"Math",lv:"HS",set:5,round:3,f:"SA",t:"Geometry",q:"What is the formula for the surface area of a sphere?",a:"4*pi*r^2",b:"What is the formula for the volume of a cylinder?",ba:"pi*r^2*h"},
  {s:"Math",lv:"HS",set:5,round:4,f:"MC",t:"Combinatorics",q:"In how many ways can a president, vice president, and secretary be chosen from 10 people?",o:{W:"120",X:"720",Y:"1000",Z:"30"},a:"X",b:"How many ways can you choose 3 items from 10 without regard to order?",ba:"120"},
  {s:"Math",lv:"HS",set:5,round:4,f:"SA",t:"Algebra",q:"What is the sum of the roots of x^2 - 5x + 6 = 0?",a:"5",b:"What is the product of the roots of x^2 - 5x + 6 = 0?",ba:"6"},
  {s:"Math",lv:"HS",set:5,round:5,f:"MC",t:"Trigonometry",q:"What is the value of sin(pi/4)?",o:{W:"1/2",X:"sqrt(2)/2",Y:"sqrt(3)/2",Z:"1"},a:"X",b:"What is the value of cos(pi/6)?",ba:"sqrt(3)/2"},
  {s:"Math",lv:"HS",set:5,round:5,f:"SA",t:"Number Theory",q:"What is the sum of the first 100 positive integers?",a:"5050",b:"What formula gives the sum of the first n positive integers?",ba:"n(n+1)/2"},
  {s:"Math",lv:"HS",set:6,round:1,f:"MC",t:"Calculus",q:"What is L'Hopital's rule used for?",o:{W:"Finding derivatives of products",X:"Evaluating limits of indeterminate forms",Y:"Integrating rational functions",Z:"Solving differential equations"},a:"X",b:"What are the two most common indeterminate forms L'Hopital's rule resolves?",ba:"0/0 and infinity/infinity"},
  {s:"Math",lv:"HS",set:6,round:1,f:"SA",t:"Probability",q:"What is the probability that at least one head appears in 3 fair coin flips?",a:"7/8",b:"What rule is used to find P(at least one)?",ba:"P(at least one) = 1 - P(none)"},
  {s:"Math",lv:"HS",set:6,round:2,f:"MC",t:"Geometry",q:"What is the measure of each interior angle of a regular octagon?",o:{W:"120 degrees",X:"135 degrees",Y:"144 degrees",Z:"150 degrees"},a:"X",b:"What is the measure of each interior angle of a regular pentagon?",ba:"108 degrees"},
  {s:"Math",lv:"HS",set:6,round:2,f:"SA",t:"Algebra",q:"What are the solutions to x^2 + 4x + 5 = 0?",a:"x = -2 plus or minus i",b:"What is the discriminant of x^2 + 4x + 5 = 0?",ba:"-4"},
  {s:"Math",lv:"HS",set:6,round:3,f:"MC",t:"Calculus",q:"What is the derivative of x^x?",o:{W:"x^x",X:"x*x^(x-1)",Y:"x^x*(1 + ln x)",Z:"x^x * ln x"},a:"Y",b:"What technique is used to differentiate x^x?",ba:"Logarithmic differentiation"},
  {s:"Math",lv:"HS",set:6,round:3,f:"SA",t:"Number Theory",q:"Is the square root of 2 rational or irrational?",a:"Irrational",b:"What proof technique shows sqrt(2) is irrational?",ba:"Proof by contradiction"},
  {s:"Math",lv:"HS",set:6,round:4,f:"MC",t:"Statistics",q:"What does a correlation coefficient r = 0 between two variables indicate?",o:{W:"Perfect positive linear relationship",X:"Perfect negative linear relationship",Y:"No linear relationship",Z:"Moderate positive relationship"},a:"Y",b:"What does r = -1 indicate?",ba:"Perfect negative linear relationship"},
  {s:"Math",lv:"HS",set:6,round:4,f:"SA",t:"Geometry",q:"In a circle, what is the relationship between a central angle and the arc it subtends?",a:"A central angle equals the arc it intercepts (in degrees)",b:"What is an inscribed angle's relationship to the arc it intercepts?",ba:"The inscribed angle is half the central angle"},
  {s:"Math",lv:"HS",set:6,round:5,f:"MC",t:"Combinatorics",q:"What is the coefficient of x^3*y^2 in the expansion of (x + y)^5?",o:{W:"5",X:"10",Y:"15",Z:"20"},a:"X",b:"What formula gives the coefficients in the binomial expansion?",ba:"C(n,k) = n! / (k!(n-k)!)"},
  {s:"Math",lv:"HS",set:6,round:5,f:"SA",t:"Calculus",q:"What is the formula for the arc length of a curve y = f(x) from x = a to x = b?",a:"L = integral from a to b of sqrt(1 + (dy/dx)^2) dx",b:"What is the formula for surface area of revolution about the x-axis?",ba:"SA = 2*pi * integral of y*sqrt(1 + (dy/dx)^2) dx"},
];