// DOE National Science Bowl - Physics Questions

export const PHYSICS_HS = [
  // SET 1
  {s:"Physics",lv:"HS",set:1,round:1,f:"SA",t:"Waves",q:"What is the term for the number of complete wave cycles that pass a given point per second?",a:"Frequency",b:"What is the relationship between wave speed, frequency, and wavelength?",ba:"v = fλ"},
  {s:"Physics",lv:"HS",set:1,round:1,f:"MC",t:"Optics",q:"What phenomenon causes light to bend when it passes from one medium to another?",o:{W:"Reflection",X:"Diffraction",Y:"Refraction",Z:"Polarization"},a:"Y",b:"What is the name of the law that relates the angles of incidence and refraction?",ba:"Snell's Law"},
  {s:"Physics",lv:"HS",set:1,round:2,f:"MC",t:"Thermodynamics",q:"Which law of thermodynamics states that heat cannot spontaneously flow from a cooler body to a warmer body?",o:{W:"Zeroth Law",X:"First Law",Y:"Second Law",Z:"Third Law"},a:"Y",b:"What is the efficiency of a Carnot engine operating between 500 K and 300 K?",ba:"40%"},
  {s:"Physics",lv:"HS",set:1,round:2,f:"SA",t:"Mechanics",q:"What is the term for the tendency of an object to resist changes in its state of motion?",a:"Inertia",b:"What is the SI unit of momentum?",ba:"kg·m/s"},
  {s:"Physics",lv:"HS",set:1,round:3,f:"MC",t:"Electromagnetism",q:"What is the direction of the magnetic force on a positive charge moving to the right through a magnetic field pointing out of the page?",o:{W:"To the left",X:"Upward",Y:"Downward",Z:"Into the page"},a:"W",b:"What is the SI unit of magnetic flux density?",ba:"Tesla"},
  {s:"Physics",lv:"HS",set:1,round:3,f:"MC",t:"Modern Physics",q:"What phenomenon demonstrated that light behaves as particles, for which Einstein received the Nobel Prize?",o:{W:"Compton scattering",X:"Photoelectric effect",Y:"Double-slit experiment",Z:"Blackbody radiation"},a:"X",b:"What is the formula for the energy of a photon?",ba:"E = hf"},
  {s:"Physics",lv:"HS",set:1,round:4,f:"SA",t:"Mechanics",q:"What is the name of Newton's third law principle that states every action has an equal and opposite reaction?",a:"Law of action and reaction",b:"What is the formula for gravitational potential energy?",ba:"PE = mgh"},
  {s:"Physics",lv:"HS",set:1,round:4,f:"MC",t:"Waves",q:"What type of wave requires a medium to travel through?",o:{W:"Electromagnetic waves",X:"Light waves",Y:"Mechanical waves",Z:"Radio waves"},a:"Y",b:"What is the speed of sound in air at room temperature, approximately?",ba:"343 m/s"},
  {s:"Physics",lv:"HS",set:1,round:5,f:"SA",t:"Optics",q:"What is the critical angle phenomenon called when light traveling in a denser medium hits a boundary at an angle greater than the critical angle?",a:"Total internal reflection",b:"What type of lens is used to correct nearsightedness?",ba:"Concave (diverging) lens"},
  {s:"Physics",lv:"HS",set:1,round:5,f:"MC",t:"Mechanics",q:"A ball is thrown horizontally from a cliff. Which best describes its motion?",o:{W:"Constant velocity in both directions",X:"Acceleration in both directions",Y:"Constant horizontal velocity and downward acceleration",Z:"Decreasing speed in both directions"},a:"Y",b:"What is the acceleration due to gravity on Earth's surface?",ba:"9.8 m/s²"},
  // SET 2
  {s:"Physics",lv:"HS",set:2,round:1,f:"MC",t:"Electricity",q:"Three resistors of 2Ω, 3Ω, and 6Ω are connected in parallel. What is the equivalent resistance?",o:{W:"11 Ω",X:"1 Ω",Y:"0.5 Ω",Z:"3 Ω"},a:"X",b:"What is the power dissipated by a 10Ω resistor carrying 2A of current?",ba:"40 W"},
  {s:"Physics",lv:"HS",set:2,round:1,f:"SA",t:"Modern Physics",q:"What is the name of the principle stating that the position and momentum of a particle cannot both be known exactly simultaneously?",a:"Heisenberg uncertainty principle",b:"What is the de Broglie wavelength formula?",ba:"λ = h/p"},
  {s:"Physics",lv:"HS",set:2,round:2,f:"MC",t:"Mechanics",q:"What is the work done by a force of 10 N moving an object 5 meters in the direction of the force?",o:{W:"2 J",X:"15 J",Y:"50 J",Z:"500 J"},a:"Y",b:"A 2 kg object moving at 3 m/s has what kinetic energy?",ba:"9 J"},
  {s:"Physics",lv:"HS",set:2,round:2,f:"SA",t:"Electromagnetism",q:"What is Faraday's law of electromagnetic induction?",a:"The induced EMF in a circuit is proportional to the rate of change of magnetic flux through the circuit",b:"What is the unit of magnetic flux?",ba:"Weber (Wb)"},
  {s:"Physics",lv:"HS",set:2,round:3,f:"MC",t:"Thermodynamics",q:"What is the specific heat capacity of water in SI units?",o:{W:"1 J/(kg·K)",X:"4186 J/(kg·K)",Y:"2257 J/(kg·K)",Z:"418.6 J/(kg·K)"},a:"X",b:"How much heat is required to raise 2 kg of water by 5°C?",ba:"41,860 J (41.86 kJ)"},
  {s:"Physics",lv:"HS",set:2,round:3,f:"SA",t:"Mechanics",q:"What is the angular momentum of a 2 kg mass moving at 3 m/s in a circle of radius 4 m?",a:"24 kg·m²/s",b:"What is the SI unit of angular momentum?",ba:"kg·m²/s"},
  {s:"Physics",lv:"HS",set:2,round:4,f:"MC",t:"Waves",q:"If the frequency of a wave doubles while the wave speed remains constant, what happens to the wavelength?",o:{W:"It doubles",X:"It quadruples",Y:"It halves",Z:"It remains the same"},a:"Y",b:"What is the Doppler effect?",ba:"The change in observed frequency due to relative motion between source and observer"},
  {s:"Physics",lv:"HS",set:2,round:4,f:"SA",t:"Optics",q:"What is the focal length of a converging lens with a power of +4 diopters?",a:"0.25 m (25 cm)",b:"What is the unit of lens power?",ba:"Diopter"},
  {s:"Physics",lv:"HS",set:2,round:5,f:"MC",t:"Modern Physics",q:"What is the name of the experiment that showed that the nucleus is dense and positively charged?",o:{W:"Double-slit experiment",X:"Millikan oil drop experiment",Y:"Rutherford gold foil experiment",Z:"Michelson-Morley experiment"},a:"Y",b:"What atomic model replaced the Thomson plum pudding model?",ba:"Rutherford's nuclear model"},
  {s:"Physics",lv:"HS",set:2,round:5,f:"SA",t:"Electricity",q:"What is Kirchhoff's junction rule?",a:"The sum of currents entering a junction equals the sum of currents leaving it",b:"What is Kirchhoff's loop rule?",ba:"The sum of all voltages around any closed loop is zero"},
  // SET 3
  {s:"Physics",lv:"HS",set:3,round:1,f:"MC",t:"Mechanics",q:"What is the moment of inertia of a point mass m at a distance r from the axis of rotation?",o:{W:"mr",X:"mr²",Y:"m²r",Z:"½mr²"},a:"X",b:"What is the rotational analog of force?",ba:"Torque"},
  {s:"Physics",lv:"HS",set:3,round:1,f:"SA",t:"Thermodynamics",q:"What is the name of the process in which a gas expands without exchanging heat with its surroundings?",a:"Adiabatic process",b:"What is the name of the process at constant pressure?",ba:"Isobaric process"},
  {s:"Physics",lv:"HS",set:3,round:2,f:"MC",t:"Electromagnetism",q:"What is the force between two parallel wires carrying current in the same direction?",o:{W:"Repulsive",X:"Attractive",Y:"Zero",Z:"It depends on the material"},a:"X",b:"What is the force between two parallel wires carrying currents in opposite directions?",ba:"Repulsive"},
  {s:"Physics",lv:"HS",set:3,round:2,f:"SA",t:"Waves",q:"What is the term for the superposition of two waves of slightly different frequencies that produces alternating constructive and destructive interference?",a:"Beats",b:"What is the formula for beat frequency?",ba:"f_beat = |f1 - f2|"},
  {s:"Physics",lv:"HS",set:3,round:3,f:"MC",t:"Modern Physics",q:"What is the name of the model of the atom that includes quantized energy levels based on wave mechanics?",o:{W:"Bohr model",X:"Rutherford model",Y:"Quantum mechanical model",Z:"Thomson model"},a:"Y",b:"What quantum number describes the spin of an electron?",ba:"Spin quantum number (ms = ±½)"},
  {s:"Physics",lv:"HS",set:3,round:3,f:"SA",t:"Mechanics",q:"What is the escape velocity from Earth's surface given g = 9.8 m/s² and Earth's radius = 6.4 × 10⁶ m?",a:"Approximately 11.2 km/s",b:"What is the formula for escape velocity?",ba:"v = √(2gR)"},
  {s:"Physics",lv:"HS",set:3,round:4,f:"MC",t:"Electricity",q:"What is the capacitance of a capacitor that stores 6 coulombs of charge when a 3-volt potential is applied?",o:{W:"0.5 F",X:"2 F",Y:"9 F",Z:"18 F"},a:"X",b:"What is the energy stored in a capacitor with capacitance C charged to voltage V?",ba:"E = ½CV²"},
  {s:"Physics",lv:"HS",set:3,round:4,f:"SA",t:"Optics",q:"What is the critical angle for total internal reflection at an air-glass interface if the index of refraction of glass is 1.5?",a:"Approximately 41.8°",b:"What is the formula for the critical angle?",ba:"sin(θc) = n2/n1"},
  {s:"Physics",lv:"HS",set:3,round:5,f:"MC",t:"Mechanics",q:"What is the period of a simple pendulum of length L on Earth where g = 9.8 m/s²?",o:{W:"T = 2π√(g/L)",X:"T = 2π√(L/g)",Y:"T = π√(L/g)",Z:"T = √(L/g)"},a:"X",b:"What determines the period of a simple pendulum?",ba:"Length of the pendulum and gravitational acceleration"},
  {s:"Physics",lv:"HS",set:3,round:5,f:"SA",t:"Thermodynamics",q:"What is the change in internal energy of a system that absorbs 500 J of heat and does 200 J of work on surroundings?",a:"300 J",b:"What is the first law of thermodynamics expressed mathematically?",ba:"ΔU = Q - W"},
  // SET 4
  {s:"Physics",lv:"HS",set:4,round:1,f:"MC",t:"Mechanics",q:"A 5 kg block slides down a frictionless incline of 30°. What is its acceleration?",o:{W:"4.9 m/s²",X:"9.8 m/s²",Y:"2.45 m/s²",Z:"5 m/s²"},a:"W",b:"What is the formula for the component of gravity along an incline of angle θ?",ba:"mg sin θ"},
  {s:"Physics",lv:"HS",set:4,round:1,f:"SA",t:"Electromagnetism",q:"What is the name of the law that states the line integral of the magnetic field around a closed loop equals the permeability of free space times the enclosed current?",a:"Ampere's Law",b:"What is Maxwell's addition to Ampere's Law?",ba:"Displacement current (changing electric flux also produces a magnetic field)"},
  {s:"Physics",lv:"HS",set:4,round:2,f:"MC",t:"Modern Physics",q:"What is the name of the series of hydrogen spectral lines in the ultraviolet region?",o:{W:"Balmer series",X:"Paschen series",Y:"Lyman series",Z:"Brackett series"},a:"Y",b:"What is the energy of a photon with wavelength 200 nm (h = 6.63 × 10⁻³⁴ J·s)?",ba:"Approximately 9.95 × 10⁻¹⁹ J"},
  {s:"Physics",lv:"HS",set:4,round:2,f:"SA",t:"Electricity",q:"What is the equivalent capacitance of two 4 F capacitors connected in series?",a:"2 F",b:"What is the equivalent capacitance of two 4 F capacitors connected in parallel?",ba:"8 F"},
  {s:"Physics",lv:"HS",set:4,round:3,f:"MC",t:"Waves",q:"What is the phenomenon in which a wave bends around obstacles or spreads after passing through small openings?",o:{W:"Reflection",X:"Refraction",Y:"Diffraction",Z:"Interference"},a:"Y",b:"What is the condition for constructive interference of two waves?",ba:"Path difference is a whole number multiple of the wavelength"},
  {s:"Physics",lv:"HS",set:4,round:3,f:"SA",t:"Thermodynamics",q:"What is Boyle's Law?",a:"At constant temperature, the pressure and volume of a gas are inversely proportional (PV = constant)",b:"What is a process called when it occurs without change in entropy?",ba:"Isentropic (or reversible adiabatic) process"},
  {s:"Physics",lv:"HS",set:4,round:4,f:"MC",t:"Mechanics",q:"Which of the following is conserved in an elastic collision?",o:{W:"Kinetic energy only",X:"Momentum only",Y:"Both kinetic energy and momentum",Z:"Neither kinetic energy nor momentum"},a:"Y",b:"What is conserved in an inelastic collision?",ba:"Momentum (but not kinetic energy)"},
  {s:"Physics",lv:"HS",set:4,round:4,f:"SA",t:"Optics",q:"What is the index of refraction of a medium in which light travels at 2 × 10⁸ m/s?",a:"1.5",b:"What is the relationship between speed of light and index of refraction?",ba:"n = c/v"},
  {s:"Physics",lv:"HS",set:4,round:5,f:"MC",t:"Electromagnetism",q:"What is the electric field inside a conductor in electrostatic equilibrium?",o:{W:"Maximum at the center",X:"Equal throughout",Y:"Zero",Z:"Dependent on the shape"},a:"Y",b:"Where does excess charge reside on a conductor in electrostatic equilibrium?",ba:"On the outer surface"},
  {s:"Physics",lv:"HS",set:4,round:5,f:"SA",t:"Mechanics",q:"What is the orbital velocity of a satellite orbiting Earth at a height where g = 8 m/s² and the radius is 7 × 10⁶ m?",a:"Approximately 7483 m/s (≈ 7.5 km/s)",b:"What is the formula for orbital velocity?",ba:"v = √(gr)"},
];

export const PHYSICS_MS = [
  {s:"Physics",lv:"MS",set:1,round:1,f:"MC",t:"Forces",q:"What is the force that pulls objects toward the center of Earth?",o:{W:"Friction",X:"Magnetism",Y:"Gravity",Z:"Tension"},a:"Y",b:"What is the unit of force in the metric system?",ba:"Newton"},
  {s:"Physics",lv:"MS",set:1,round:1,f:"SA",t:"Energy",q:"What type of energy does a moving object have?",a:"Kinetic energy",b:"What type of energy is stored energy due to position?",ba:"Potential energy"},
  {s:"Physics",lv:"MS",set:1,round:2,f:"MC",t:"Light",q:"What is the speed of light in a vacuum approximately?",o:{W:"300 km/s",X:"3,000 km/s",Y:"300,000 km/s",Z:"3,000,000 km/s"},a:"Y",b:"What is the bending of light as it passes through different materials called?",ba:"Refraction"},
  {s:"Physics",lv:"MS",set:1,round:2,f:"SA",t:"Electricity",q:"What do you call a material that allows electricity to flow through it easily?",a:"Conductor",b:"What do you call a material that does not allow electricity to flow?",ba:"Insulator"},
  {s:"Physics",lv:"MS",set:2,round:1,f:"MC",t:"Sound",q:"What is the unit used to measure the loudness of sound?",o:{W:"Hertz",X:"Decibel",Y:"Watt",Z:"Joule"},a:"X",b:"Does sound travel faster through air or water?",ba:"Water"},
  {s:"Physics",lv:"MS",set:2,round:1,f:"SA",t:"Forces",q:"What is the formula for calculating work?",a:"Work = Force × Distance (W = Fd)",b:"What is the unit of work?",ba:"Joule"},
  {s:"Physics",lv:"MS",set:2,round:2,f:"MC",t:"Machines",q:"What is the mechanical advantage of a lever with an effort arm of 4 m and a load arm of 1 m?",o:{W:"0.25",X:"1",Y:"4",Z:"5"},a:"Y",b:"What simple machine consists of a wheel and axle combination?",ba:"Wheel and axle"},
  {s:"Physics",lv:"MS",set:3,round:1,f:"SA",t:"Waves",q:"What is the distance between two consecutive crests of a wave?",a:"Wavelength",b:"What is the height of a wave from its rest position to its crest?",ba:"Amplitude"},
];