// DOE National Science Bowl - Physics Extra Questions (Sets 5-6)

export const PHYSICS_HS_EXT = [
  {s:"Physics",lv:"HS",set:5,round:1,f:"MC",t:"Mechanics",q:"A car travels 60 km in 1 hour, then 40 km in 30 minutes. What is the average speed for the entire trip?",o:{W:"50 km/h",X:"66.7 km/h",Y:"100 km/h",Z:"50.5 km/h"},a:"X",b:"What is the difference between average speed and average velocity?",ba:"Speed is distance/time (scalar); velocity is displacement/time (vector)"},
  {s:"Physics",lv:"HS",set:5,round:1,f:"SA",t:"Thermodynamics",q:"What is the name of the process in which a gas is compressed so slowly that temperature remains constant?",a:"Isothermal process",b:"What is the name of the process at constant volume?",ba:"Isochoric (isovolumetric) process"},
  {s:"Physics",lv:"HS",set:5,round:2,f:"MC",t:"Electricity",q:"What is the electric potential energy of two point charges q1 and q2 separated by distance r?",o:{W:"U = kq1q2/r^2",X:"U = kq1q2/r",Y:"U = kq1q2*r",Z:"U = k(q1+q2)/r"},a:"X",b:"What is the unit of electric potential energy?",ba:"Joule"},
  {s:"Physics",lv:"HS",set:5,round:2,f:"SA",t:"Waves",q:"What is the term for a wave that oscillates perpendicular to its direction of propagation?",a:"Transverse wave",b:"What is a wave that oscillates parallel to its direction of propagation called?",ba:"Longitudinal wave"},
  {s:"Physics",lv:"HS",set:5,round:3,f:"MC",t:"Modern Physics",q:"What experiment demonstrated the wave nature of electrons?",o:{W:"Rutherford experiment",X:"Photoelectric effect",Y:"Davisson-Germer experiment",Z:"Compton scattering"},a:"Y",b:"What hypothesis describes wave-particle duality of matter?",ba:"de Broglie hypothesis"},
  {s:"Physics",lv:"HS",set:5,round:3,f:"SA",t:"Mechanics",q:"What is the law of conservation of angular momentum?",a:"The total angular momentum of a system is constant unless acted upon by a net external torque",b:"Why does a spinning skater speed up when pulling in their arms?",ba:"Moment of inertia decreases, so angular velocity increases to conserve angular momentum"},
  {s:"Physics",lv:"HS",set:5,round:4,f:"MC",t:"Electromagnetism",q:"What is the unit of magnetic flux?",o:{W:"Tesla",X:"Weber",Y:"Henry",Z:"Farad"},a:"X",b:"What is the unit of inductance?",ba:"Henry"},
  {s:"Physics",lv:"HS",set:5,round:4,f:"SA",t:"Optics",q:"What is the image distance for an object 30 cm from a converging lens with focal length 10 cm?",a:"15 cm",b:"What is the thin lens equation?",ba:"1/f = 1/do + 1/di"},
  {s:"Physics",lv:"HS",set:5,round:5,f:"SA",t:"Mechanics",q:"What is the impulse-momentum theorem?",a:"Impulse (force times time) equals the change in momentum",b:"A force of 10 N acts for 3 seconds on a 5 kg object at rest. What is its final velocity?",ba:"6 m/s"},
  {s:"Physics",lv:"HS",set:5,round:5,f:"MC",t:"Thermodynamics",q:"Which of the following processes is irreversible?",o:{W:"Slow isothermal compression",X:"Quasi-static adiabatic expansion",Y:"Rapid free expansion of a gas into vacuum",Z:"Slow isobaric heating"},a:"Y",b:"What is the entropy change for the universe in a reversible process?",ba:"Zero"},
  {s:"Physics",lv:"HS",set:6,round:1,f:"MC",t:"Electricity",q:"What is the relationship between electric field and electric potential?",o:{W:"E = V/r^2",X:"E = -dV/dr",Y:"E = V times r",Z:"V = E^2/r"},a:"X",b:"In which direction does the electric field point?",ba:"From high potential to low potential"},
  {s:"Physics",lv:"HS",set:6,round:1,f:"SA",t:"Waves",q:"What is the name of the phenomenon where two waves overlap and combine?",a:"Superposition (or interference)",b:"What is the pattern of alternating bright and dark bands from interfering light waves?",ba:"Interference pattern"},
  {s:"Physics",lv:"HS",set:6,round:2,f:"SA",t:"Mechanics",q:"What is the term for the force that keeps a satellite in circular orbit?",a:"Centripetal force",b:"For a satellite in circular orbit, what provides the centripetal force?",ba:"Gravity"},
  {s:"Physics",lv:"HS",set:6,round:2,f:"MC",t:"Modern Physics",q:"What is the name of the antiparticle of the electron?",o:{W:"Muon",X:"Neutron",Y:"Positron",Z:"Proton"},a:"Y",b:"What is the process called when a particle meets its antiparticle and they annihilate?",ba:"Pair annihilation"},
  {s:"Physics",lv:"HS",set:6,round:3,f:"MC",t:"Electromagnetism",q:"What is the name of the law that relates magnetic field to the current that produces it?",o:{W:"Faraday's Law",X:"Lenz's Law",Y:"Biot-Savart Law",Z:"Coulomb's Law"},a:"Y",b:"What is the magnetic field at the center of a circular loop of radius r carrying current I?",ba:"B = mu0*I/(2r)"},
  {s:"Physics",lv:"HS",set:6,round:3,f:"SA",t:"Thermodynamics",q:"What is the coefficient of performance of an ideal refrigerator operating between Th and Tc?",a:"COP = Tc/(Th - Tc)",b:"How does a heat pump COP relate to a refrigerator COP?",ba:"Heat pump COP = refrigerator COP + 1"},
  {s:"Physics",lv:"HS",set:6,round:4,f:"SA",t:"Mechanics",q:"What is the name of the theorem that relates net work done on an object to its change in kinetic energy?",a:"Work-energy theorem",b:"State the work-energy theorem mathematically.",ba:"W_net = delta KE = (1/2)mv^2 - (1/2)mv0^2"},
  {s:"Physics",lv:"HS",set:6,round:4,f:"MC",t:"Optics",q:"What phenomenon causes a single-wavelength beam to split into a spectrum when passed through a diffraction grating?",o:{W:"Dispersion",X:"Diffraction",Y:"Refraction",Z:"Polarization"},a:"X",b:"What is the condition for constructive interference in a double slit?",ba:"Path difference = m*lambda (whole number multiple of wavelength)"},
  {s:"Physics",lv:"HS",set:6,round:5,f:"MC",t:"Modern Physics",q:"In the photoelectric effect, increasing the intensity of light does what?",o:{W:"Increases kinetic energy of ejected electrons",X:"Increases the number of ejected electrons",Y:"Increases the threshold frequency",Z:"Increases the stopping potential"},a:"X",b:"What is the stopping potential in the photoelectric effect?",ba:"The minimum reverse voltage needed to stop all emitted electrons"},
  {s:"Physics",lv:"HS",set:6,round:5,f:"SA",t:"Electricity",q:"What is the time constant tau for an RC circuit?",a:"tau = RC",b:"After one time constant, what fraction of initial charge remains on a discharging capacitor?",ba:"1/e (approximately 37%)"},
];